django/CRUD/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('<username>/', views.profile, name='profile'),
]

django/CRUD/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

django/CRUD/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

django/CRUD/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Article(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

django/CRUD/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        # fields = '__all__'
        exclude = ['user',]

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ['article', 'user',]

django/CRUD/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles':articles,
    }
    return render(request, 'articles/index.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        article = form.save(commit=False)
        article.user = request.user
        article.save()
        return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form':form,
    }
    return render(request, 'articles/create.html', context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm()
    comments = article.comments.all()[::-1]
    context = {
        'article':article,
        'comment_form':comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update(request,pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)

@require_POST
def delete(request, pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        article.delete()
    return redirect('articles:index')

@require_POST
def comments_create(request, pk):
    # article = Article.objects.get(pk=pk)
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Create, but don't save the new comment instance.
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
            return redirect('articles:detail', article.pk)
        context = {
            'comment_form': comment_form,
            'article': article,
        }
        return render(request, 'articles/detail.html', context)
    return redirect('accounts:login')

@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)

@require_POST
def like(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
        else:
            article.like_users.add(request.user)
        return redirect('articles:index')
    return redirect('accounts:login')

django/CRUD/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="text-center">CREATE</h3>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}

django/CRUD/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="text-center">DETAIL</h3>
  <h3>{{ article.pk }} 번 째 글</h3>
  <hr>
  <p>제목: {{ article.title }}</p>
  <p>내용: {{ article.content }}</p>
  <p>작성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
  <p>수정 시각: {{ article.updated_at|date:"M j, Y" }}</p>
  <hr>
  <h4>댓글 목록</h4>
  {% if comments|length %}
    <p>{{ comments|length }} 개의 댓글이 있습니다.</p>
  {% endif %}
  {% for comment in comments %}
    <ul>
      {{ comment.user }} : {{ comment.content }}
    </ul>
    {% if request.user == comment.user %}
      <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE">
      </form>    
    {% endif %}
  {% empty %}
    <p>댓글이 아직 없어요..</p>
  {% endfor %}
  <hr>
  {% if request.user.is_authenticated %}
    <h4>댓글 작성</h4>
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}" style="color:#f280a6">[댓글을 작성하려면 로그인 하세요.]</a>
  {% endif %}
  <hr>
  <a href="{% url 'articles:update' article.pk %}" style="color:#f280a6">[update]</a>
  <br>
  <a href="{% url 'articles:index' %}" style="color:#f280a6">[back]</a>
  <br>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
{% endblock content %}

django/CRUD/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="text-content">INDEX</h3>
  {% if request.user.is_authenticated %}
    <a href="{% url 'articles:create' %}" style="color:#f280a6">WRITE</a>
    <br>
    <a href="{% url 'accounts:update' %}" style="color:#f280a6">정보수정</a>
  {% else %}
    <a href="{% url 'accounts:login' %}" style="color:#f280a6">[새 글을 작성하려면 로그인하세요]</a>
  {% endif %}
  <hr>
  {% for article in articles %}
    <p>작성자: <a href="{% url 'accounts:profile' article.user.username %}" style="color:#f280a6">{{ article.user }}</a></p>
    <p>글 번호: {{ article.pk }}</p>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <form action="{% url 'articles:like' article.pk %}" method="POST" class="d-inline">
       {% csrf_token %}
       {% if request.user in article.like_users.all %}
        <button type="submit" class="btn btn-link" style="color:crimson;">
          <i class="fas fa-heart"></i>
        </button>
       {% else %}
        <button type="submit" class="btn btn-link" style="color:black;">
          <i class="fas fa-heart"></i>
        </button>
       {% endif %}
    </form>
    {{ article.like_users.all|length }} 명이 이 글을 좋아합니다.
    <br>
    <a href="{% url 'articles:detail' article.pk %}" style="color:#f280a6">[DETAIL]</a>
    <hr>
  {% endfor %}
{% endblock content %}

django/CRUD/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h3 class="text-center">UPDATE</h3>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="변경">
  </form>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}